[workspace]
default-members = [
	"atk",
	"atk/sys",
	"gdk",
	"gdk/sys",
	"gtk",
	"gtk/sys",
	"gtk3-macros",
]

members = [
	"atk",
	"atk/sys",
	"gdk",
	"gdk/sys",
	"gdkwayland",
	"gdkwayland/sys",
	"gdkx11",
	"gdkx11/sys",
	"gtk",
	"gtk/sys",
	"gtk3-macros",
]

exclude = ["gir", "checker"]
