// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ../gir-files
// DO NOT EDIT

use crate::{ffi, Object};
use glib::prelude::*;
use glib::translate::*;

glib::wrapper! {
    #[derive(Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
    pub struct ImplementorIFace(Interface<ffi::AtkImplementor, ffi::AtkImplementorIface>);

    match fn {
        type_ => || ffi::atk_implementor_get_type(),
    }
}
