// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ../gir-files
// DO NOT EDIT

use glib::{prelude::*};

glib::wrapper! {
    #[doc(alias = "GtkActivatable")]
    pub struct Activatable(Interface<ffi::GtkActivatable, ffi::GtkActivatableIface>);

    match fn {
        type_ => || ffi::gtk_activatable_get_type(),
    }
}

impl Activatable {
        pub const NONE: Option<&'static Activatable> = None;
    
}

mod sealed {
    pub trait Sealed {}
    impl<T: super::IsA<super::Activatable>> Sealed for T {}
}

pub trait ActivatableExt: IsA<Activatable> + sealed::Sealed + 'static {}

impl<O: IsA<Activatable>> ActivatableExt for O {}
